#!/bin/bash
#SBATCH -p gpu                   # job submitted to cpu
###SBATCH -w gpu-2                  
#SBATCH -N 1                  # 
###SBATCH --ntasks-per-node=1       # 
#SBATCH --gres=gpu:1                  

#SBATCH --cpus-per-task=4         # 
#SBATCH --mem 200G
#SBATCH -t 10-10:00:00               # 
#SBATCH -J lmdb
#SBATCH --output=lmdb-%A.out

PythonFolder=/new-stg/home/cong/miniconda3/envs/dpi/bin

#file=all_valid
#file=train_s10
#file=train
#file=test
#file=test_min10
#file=valid
file=valid_min10
#file=train_min100
#file=train_min10

data=Encode3and4
#data=Encode4
#data=Encode3
#data=ChIP_690

###$PythonFolder'/python' generate_database_for_dna_and_protein_embedding.py $file $kmer $data

$PythonFolder'/python' generate_dna_lmdb_file.py $file $data

