#!/bin/bash
#SBATCH -p gpu                   # job submitted to cpu
#SBATCH -w gpu-2                   # job submitted to cpu
###SBATCH -N 1                  # 
###SBATCH --ntasks-per-node=1       # 
###SBATCH --cpus-per-task=3         # 
#SBATCH --mem 100G
#SBATCH -t 10-10:00:00               # 
###SBATCH --array=1-3
#SBATCH -J csv
#SBATCH --output=csv-%A.out

PythonFolder=/new-stg/home/cong/miniconda3/envs/dpi/bin

$PythonFolder'/python' prepare_main_csv.py




