#!/bin/bash
###SBATCH -p gpu                   # job submitted to cpu
###SBATCH -N 1                  # 
###SBATCH --ntasks-per-node=1       # 
#SBATCH --cpus-per-task=8         # 
#SBATCH --mem 20G
#SBATCH -t 10-10:00:00               # 
#SBATCH --array=1-6


#SBATCH -J fasta
#SBATCH --output=get_fasta_v3-%A.out


input_prefix=$(sed -n -e "$SLURM_ARRAY_TASK_ID p" /new-stg/home/cong/DPI/dataset/Encode3/file_human_hg19.txt | awk '{print $1}')
echo $input_prefix


# 0. set up
inputFolder=/new-stg/home/cong/DPI/downloads/ChIP_Encode3/
outputFolder=/new-stg/home/cong/DPI/dataset/Encode3/get_fasta_results_max_512bp/

# 1. get fasta
## 1.1 extract the fixed-length sequence centered at the peak summit
awk '{if (($3-$2)>512) {print $1, $2+$10-255, $2+$10+256} else {print $1, $2, $3}}'  OFS="\t" $inputFolder$input_prefix'.bed' > $outputFolder$input_prefix'.bed'

## 1.2 get fasta
###input_prefix=ENCFF657NRR_POLR2A_GRCh38
ScriptFolder=/new-stg/home/cong/miniconda3/envs/dpi/bin/
#$ScriptFolder'bedtools' getfasta -fi $inputFolder'assembly/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta' -bed $outputFolder$input_prefix'.bed' -fo $outputFolder$input_prefix'.fasta'
$ScriptFolder'bedtools' getfasta -fi /new-stg/home/cong/DPI/downloads/ChIP_690/assembly/male.hg19.fa -bed $outputFolder$input_prefix'.bed' -fo $outputFolder$input_prefix'.fasta'

# 2. get shuffled fasta
ScriptFolder=/new-stg/home/cong/miniconda3/envs/py2/bin/
$ScriptFolder'fasta-dinucleotide-shuffle' -f $outputFolder$input_prefix'.fasta' -t _shuffled > $outputFolder$input_prefix'_shuffled.fasta'

# 3. combine fasta and shuffled fasta
ScriptFolder=/new-stg/home/cong/DPI/dataset/Encode3/
$ScriptFolder'add_labels.sh' $outputFolder $input_prefix
