#!/bin/bash
###SBATCH -p gpu                  
###SBATCH -N 1                  # 
###SBATCH --ntasks-per-node=1       # 
#SBATCH --cpus-per-task=4         # 
#SBATCH --mem 100G
#SBATCH -t 10-10:00:00               # 
#SBATCH -J pair
#SBATCH --output=balance-%A.out

PythonFolder=/new-stg/home/cong/miniconda3/envs/dpi/bin


#file=train
#file=valid
#file=valid_min10
#file=test


dataset=ChIP_690
#dataset=Encode4
#dataset=Encode3and4
#dataset=Encode3

#n=20000
#n=3000
#n=6000

#for file in train_min10 test_min10 valid_min10
for file in train test valid

do
    $PythonFolder'/python' further_balance_ratio_by_proteins.py $dataset $file
done

#$PythonFolder'/python' further_balance_ratio_by_proteins.py $dataset $file



