#!/bin/bash
###SBATCH -p gpu                   # job submitted to cpu
###SBATCH -N 1                  # 
###SBATCH --ntasks-per-node=1       # 
#SBATCH --cpus-per-task=8         # 
#SBATCH --mem 20G
#SBATCH -t 10-10:00:00               # 
###SBATCH --array=1-3

#SBATCH -J fasta
###SBATCH --output=get_fasta-%A-%a.out
#SBATCH --output=get_fasta-%A.out


#start_loc=$(sed -n -e "$SLURM_ARRAY_TASK_ID p" /new-stg/home/cong/DPI/dataset/ChIP_690/start_loc.txt | awk '{print $1}')
#echo $start_loc


# 0. set up
inputFolder=/new-stg/home/cong/DPI/downloads/ChIP_Encode3/
outputFolder=/new-stg/home/cong/DPI/dataset/Encode3/get_fasta_results/
readarray -t files < $inputFolder'file_id2.txt'

for input_prefix in "${files[@]}"
do
   echo "$input_prefix"

    # 1. get fasta
    ###input_prefix=ENCFF657NRR_POLR2A_GRCh38
    ScriptFolder=/new-stg/home/cong/miniconda3/envs/dpi/bin/
    $ScriptFolder'bedtools' getfasta -fi $inputFolder'assembly/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta' -bed $inputFolder$input_prefix'.bed' -fo $outputFolder$input_prefix'.fasta'

    # 2. get shuffled fasta
    ScriptFolder=/new-stg/home/cong/miniconda3/envs/py2/bin/
    $ScriptFolder'fasta-dinucleotide-shuffle' -f $outputFolder$input_prefix'.fasta' -t _shuffled > $outputFolder$input_prefix'_shuffled.fasta'

    # 3. combine fasta and shuffled fasta
    ScriptFolder=/new-stg/home/cong/DPI/dataset/Encode3/
    $ScriptFolder'add_labels.sh' $outputFolder $input_prefix

done
